namespace Sudoku.Contracts;

public sealed record TrainingRunRealtimeApiResponse(
    string MessageKind,
    string RunName,
    string Status,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? UpdatedAtUtc,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset? FinishedAtUtc,
    string BaseModelName,
    string ProducedModelName,
    string ProcessedDatasetName,
    string TrainingMode,
    string TrainingProfileName,
    string AugmentationProfileName,
    string BenchmarkName,
    int Seed,
    long? LastAcceptedSequence,
    string? LastEventType,
    TrainingRunProgressApiResponse? Progress,
    TrainingMetricsSummaryApiResponse? MetricsSummary,
    string? ReportStatus,
    string? ReportRelativePath,
    IReadOnlyList<string> Warnings,
    IReadOnlyList<string> CleanupWarnings,
    string? FailureReason);
