namespace Sudoku.Application.Trainings;

public sealed record TrainingRunMetadataDto(
    string RunName,
    string Status,
    DateTimeOffset CreatedAtUtc,
    string BaseModelName,
    string ProducedModelName,
    string ProcessedDatasetName,
    string TrainingMode,
    string TrainingProfileName,
    string AugmentationProfileName,
    string BenchmarkName,
    int Seed,
    string ProgressChannelUrl,
    DateTimeOffset? UpdatedAtUtc = null,
    string? SourceRevision = null,
    string? ReportStatus = null,
    IReadOnlyList<string>? Warnings = null,
    string? MlJobId = null,
    long? LastAcceptedSequence = null,
    string? LastEventType = null,
    DateTimeOffset? StartedAtUtc = null,
    DateTimeOffset? FinishedAtUtc = null,
    TrainingRunProgressDto? Progress = null,
    string? ReportRelativePath = null,
    TrainingMetricsSummaryDto? MetricsSummary = null,
    string? FailureReason = null,
    IReadOnlyList<string>? CleanupWarnings = null);
