MODEL_MANIFEST_FILE_NAME = "model.json"
ARTIFACTS_DIRECTORY_NAME = "artifacts"
DEFAULT_PRIMARY_ARTIFACT_RELATIVE_PATH = "artifacts/model.pt"
ACTIVE_MODEL_FILE_NAME = "inference.json"

ENVIRONMENT_VARIABLE_NAME = "ML_ENVIRONMENT"
BOOTSTRAP_MODELS_JSON_VARIABLE_NAME = "ML_BOOTSTRAP_MODELS_JSON"
BOOTSTRAP_OVERWRITE_EXISTING_VARIABLE_NAME = (
    "ML_BOOTSTRAP_OVERWRITE_EXISTING"
)
BOOTSTRAP_SET_ACTIVE_IF_MISSING_VARIABLE_NAME = (
    "ML_BOOTSTRAP_SET_ACTIVE_IF_MISSING"
)
BOOTSTRAP_DEFAULT_ACTIVE_MODEL_VARIABLE_NAME = (
    "ML_BOOTSTRAP_DEFAULT_ACTIVE_MODEL"
)

REGISTRY_DIRECTORY_VARIABLE_NAMES = (
    "ML_MODELS_REGISTRY_DIRECTORY_PATH",
    "ML_MODELS_REGISTRY_DIR",
)
ACTIVE_MODEL_DIRECTORY_VARIABLE_NAMES = (
    "ML_ACTIVE_MODEL_DIRECTORY_PATH",
    "ML_MODELS_ACTIVE_DIR",
)

STATUS_CREATED = "created"
STATUS_SKIPPED = "skipped"
STATUS_FAILED = "failed"

SOURCE_TYPE_BOOTSTRAP = "bootstrap"
FRAMEWORK_PYTORCH = "pytorch"
ARTIFACT_FORMAT_PYTORCH_STATE_DICT = "pytorch-state-dict"

