name: Only dev can merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"

          if [ "${{ github.base_ref }}" != "main" ]; then
            echo "PR is not targeting main, skipping."
            exit 0
          fi

          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only pull requests from 'dev' to 'main' are allowed."
            exit 1
          fi
